export const MOCK_APPOINTMENTS = [
  {
    id: 'a001',
    department: 'Cardiology',
    doctor: 'Dr. Rohit Nair',
    specialization: 'Interventional Cardiology',
    date: '2026-02-10',
    time: '11:00 AM',
    tokenNumber: 7,
    stage: 'Completed',
    status: 'Completed',
    notes: 'ECG normal. Lipid profile advised. Follow-up in 4 weeks.',
  },
  {
    id: 'a002',
    department: 'Dermatology',
    doctor: 'Dr. Meera Iyer',
    specialization: 'Clinical Dermatology',
    date: '2026-01-28',
    time: '10:15 AM',
    tokenNumber: 3,
    stage: 'Completed',
    status: 'Completed',
    notes:
      'Mild eczema. Prescribed topical cream. No further follow-up needed.',
  },
  {
    id: 'a003',
    department: 'Ophthalmology',
    doctor: 'Dr. Suresh Pillai',
    specialization: 'Retinal Surgery',
    date: '2026-01-12',
    time: '09:30 AM',
    tokenNumber: 11,
    stage: 'Completed',
    status: 'Completed',
    notes: 'Visual acuity 6/6 both eyes. Advised annual screening.',
  },
  {
    id: 'a004',
    department: 'ENT',
    doctor: 'Dr. Vikram Bose',
    specialization: 'Otolaryngology',
    date: '2026-01-05',
    time: '02:00 PM',
    tokenNumber: 5,
    stage: 'Completed',
    status: 'Completed',
    notes: 'Acute sinusitis. Course of antibiotics prescribed. Resolved.',
  },
  {
    id: 'a005',
    department: 'Orthopaedics',
    doctor: 'Dr. Anand Krishnan',
    specialization: 'Joint Replacement',
    date: '2025-12-20',
    time: '11:45 AM',
    tokenNumber: 9,
    stage: 'Completed',
    status: 'Cancelled',
    notes: 'Patient cancelled appointment. No record of visit.',
  },
];
